version: 2.1

executors:
  gradle-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  build:
    executor: gradle-executor
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Build Project
          command: ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/

workflows:
  version: 2
  build:
    jobs:
      - build
